### ISSUE TITLE
Need support for Okta integration and Role based authentication

### ISSUE THREAD

**Issue by yrsurya** [jenkinsci/configuration-as-code-plugin#910]
### Your checklist for this issue

🚨 Please review the [guidelines for contributing](../blob/master/docs/CONTRIBUTING.md) to this repository.

- [ ] Link to any upstream changes that might be required (for example Jenkins Core pull request)

### Feature Request

Describe your feature request here.
 we are trying to make our jenkins completely as JASC but as it not supporting okta/role based authentication we are holding this now so please let us know when this can be implemented

**Comment by casz** [comment]
Okta is supported in SAML plugin https://support.cloudbees.com/hc/en-us/articles/115000105752-How-do-I-setup-OKTA-as-Identity-Provider-in-Jenkins-
[Role strategy plugin](https://github.com/jenkinsci/role-strategy-plugin) supports role-based auth

So your all good to go? or did the google stop working?

**Comment by casz** [comment]
We even have demos on how to configure [saml](https://github.com/jenkinsci/configuration-as-code-plugin/blob/master/demos/saml/README.md) and [role-strategy-plugin](https://github.com/jenkinsci/configuration-as-code-plugin/blob/master/demos/role-strategy-auth/README.md)

**Comment by yrsurya** [comment]
we are seeing following error while trying to export current configuration

 authorizationStrategy: "FAILED TO EXPORT hudson.model.Hudson#authorizationStrategy:\
    \ io.jenkins.plugins.casc.ConfiguratorException: Can't read attribute 'roles'\
    \ from com.michelin.cio.hudson.plugins.rolestrategy.RoleBasedAuthorizationStrategy@4e2c90c1\
    \  at io.jenkins.plugins.casc.Attribute._getValue(Attribute.java:256)  at io.jenkins.plugins.casc.Attribute.getValue(Attribute.java:175)\
    \  at io.jenkins.plugins.casc.Attribute.equals(Attribute.java:206)  at io.jenkins.plugins.casc.BaseConfigurator.compare(BaseConfigurator.java:384)\
    \  at io.jenkins.plugins.casc.support.rolestrategy.RoleBasedAuthorizationStrategyConfigurator.describe(RoleBasedAuthorizationStrategyConfigurator.java:57)\
    \  at io.jenkins.plugins.casc.support.rolestrategy.RoleBasedAuthorizationStrategyConfigurator.describe(RoleBasedAuthorizationStrategyConfigurator.java:25)\
    \  at io.jenkins.plugins.casc.impl.configurators.HeteroDescribableConfigurator.lambda$convertToNode$de0cd4f8$1(HeteroDescribableConfigurator.java:233)\
    \  at io.vavr.CheckedFunction0.lambda$unchecked$52349c75$1(CheckedFunction0.java:201)\
    \  at io.jenkins.plugins.casc.impl.configurators.HeteroDescribableConfigurator.convertToNode(HeteroDescribableConfigurator.java:233)\
    \  at io.jenkins.plugins.casc.impl.configurators.HeteroDescribableConfigurator.lambda$describe$5(HeteroDescribableConfigurator.java:103)\
    \  at io.vavr.control.Option.map(Option.java:373)  at io.jenkins.plugins.casc.impl.configurators.HeteroDescribableConfigurator.describe(HeteroDescribableConfigurator.java:103)\
    \  at io.jenkins.plugins.casc.impl.configurators.HeteroDescribableConfigurator.describe(HeteroDescribableConfigurator.java:51)\
    \  at io.jenkins.plugins.casc.Attribute.describe(Attribute.java:197)  at io.jenkins.plugins.casc.Configurator.describe(Configurator.java:162)"

**Comment by casz** [comment]
Please use the latest version of JCasC 1.19
Read the demo example. It says
> Requires role-strategy >= 2.11

**Comment by yrsurya** [comment]
Able to resolve the issue after upgrading but still seeing  this

credentials:
  system:
    domainCredentials:
    - credentials: "FAILED TO EXPORT com.cloudbees.plugins.credentials.domains.DomainCredentials#credentials:\
        \ java.lang.NullPointerException  at io.jenkins.plugins.casc.impl.configurators.DataBoundConfigurator.describe(DataBoundConfigurator.java:240)\
        \  at io.jenkins.plugins.casc.impl.configurators.HeteroDescribableConfigurator.lambda$convertToNode$de0cd4f8$1(HeteroDescribableConfigurator.java:224)\
        \  at io.vavr.CheckedFunction0.lambda$unchecked$52349c75$1(CheckedFunction0.java:201)\
        \  at io.jenkins.plugins.casc.impl.configurators.HeteroDescribableConfigurator.convertToNode(HeteroDescribableConfigurator.java:224)\
        \  at io.jenkins.plugins.casc.impl.configurators.HeteroDescribableConfigurator.lambda$describe$5(HeteroDescribableConfigurator.java:103)\
        \  at io.vavr.control.Option.map(Option.java:373)  at io.jenkins.plugins.casc.impl.configurators.HeteroDescribableConfigurator.describe(HeteroDescribableConfigurator.java:103)\
        \  at io.jenkins.plugins.casc.impl.configurators.HeteroDescribableConfigurator.describe(HeteroDescribableConfigurator.java:51)\
        \  at io.jenkins.plugins.casc.Attribute.describe(Attribute.java:194)  at io.jenkins.plugins.casc.impl.configurators.DataBoundConfigurator.describe(DataBoundConfigurator.java:264)\
        \  at io.jenkins.plugins.casc.Attribute.describe(Attribute.java:194)  at com.cloudbees.plugins.credentials.casc.SystemCredentialsProviderConfigurator.describe(SystemCredentialsProviderConfigurator.java:76)\
        \  at com.cloudbees.plugins.credentials.casc.SystemCredentialsProviderConfigurator.describe(SystemCredentialsProviderConfigurator.java:48)\
        \  at io.jenkins.plugins.casc.Attribute.describe(Attribute.java:198)  at com.cloudbees.plugins.credentials.casc.CredentialsRootConfigurator.describe(CredentialsRootConfigurator.java:90)\
        \  at com.cloudbees.plugins.credentials.casc.CredentialsRootConfigurator.describe(CredentialsRootConfigurator.java:52)"

**Comment by casz** [comment]
@yrsurya please read the release notes before updating 😓
https://github.com/jenkinsci/configuration-as-code-plugin/releases/tag/configuration-as-code-1.18
Remove [Credentials Plugin](https://plugins.jenkins.io/credentials) from Support plugin. Use Credentials 2.2.0+ instead

**Comment by yrsurya** [comment]
sorry for the trouble but we are using the latest version of the credntial plugin and removed JCAC support plugin. let me update Jenkins to latest LTS and test again


  | Credentials PluginThis plugin allows you to store credentials in Jenkins. | 2.2.0 | Downgrade to 2.1.19
-- | -- | -- | --

**Comment by casz** [comment]
Could you share with me your current YAML file that you use to configure your instance? 
Please also share me which credentials type you currently have configured inside the instance.
Could you also share the full plugin list?

**Comment by casz** [comment]
@yrsurya you can run this in the [script console](https://wiki.jenkins.io/display/JENKINS/Jenkins+Script+Console) to find the plugins and credential types your using:

```
def credentials_store = jenkins.model.Jenkins.instance.getExtensionList('com.cloudbees.plugins.credentials.SystemCredentialsProvider')
credentials_store[0].credentials.each { it ->
    println "credentials: -> ${it}"
}
Jenkins.instance.pluginManager.plugins.each{
  plugin -> 
    println ("${plugin.getShortName()}: ${plugin.getVersion()}")
}
```

It outputs something like this
```
credentials: -> com.cloudbees.plugins.credentials.impl.UsernamePasswordCredentialsImpl@bca4ffe4
credentials: -> com.cloudbees.plugins.credentials.impl.UsernamePasswordCredentialsImpl@2cb7b7c3
credentials: -> com.cloudbees.plugins.credentials.impl.UsernamePasswordCredentialsImpl@cfc4626
credentials: -> com.cloudbees.jenkins.plugins.sshcredentials.impl.BasicSSHUserPrivateKey@6d1a6be4
credentials: -> com.dabsquared.gitlabjenkins.connection.GitLabApiTokenImpl@ad94bd35
credentials: -> org.jenkinsci.plugins.plaincredentials.impl.StringCredentialsImpl@bb56017c
credentials: -> com.cloudbees.plugins.credentials.impl.UsernamePasswordCredentialsImpl@ce0e7f6b
credentials: -> com.datapipe.jenkins.vault.credentials.VaultAppRoleCredential@a1cffd1c
blueocean-core-js: 1.17.0
blueocean-display-url: 2.3.0
pipeline-stage-step: 2.3
blueocean-bitbucket-pipeline: 1.17.0
matrix-auth: 2.4.2
pipeline-model-declarative-agent: 1.1.1
mercurial: 2.6
variant: 1.2
analysis-model-api: 5.1.1
description-setter: 1.10
mstest: 1.0.0
jdk-tool: 1.2
workflow-api: 2.35
blueocean-commons: 1.17.0
ssh-slaves: 1.30.0
blueocean-rest: 1.17.0
xunit: 2.3.3
blueocean-events: 1.17.0
workflow-aggregator: 2.6
node-iterator-api: 1.5.0
```

**Comment by yrsurya** [comment]
credentials: -> com.cloudbees.plugins.credentials.impl.UsernamePasswordCredentialsImpl@8418f71a
credentials: -> com.cloudbees.plugins.credentials.impl.UsernamePasswordCredentialsImpl@5de67046
credentials: -> com.cloudbees.plugins.credentials.impl.UsernamePasswordCredentialsImpl@3ed176d3
credentials: -> com.cloudbees.jenkins.plugins.sshcredentials.impl.BasicSSHUserPrivateKey@be348040
credentials: -> com.cloudbees.jenkins.plugins.sshcredentials.impl.BasicSSHUserPrivateKey@aa03297a
credentials: -> com.cloudbees.plugins.credentials.impl.UsernamePasswordCredentialsImpl@78477e42
credentials: -> com.cloudbees.jenkins.plugins.sshcredentials.impl.BasicSSHUserPrivateKey@9bf4a920
credentials: -> com.cloudbees.jenkins.plugins.awscredentials.AWSCredentialsImpl@b3b76433
credentials: -> com.cloudbees.plugins.credentials.impl.UsernamePasswordCredentialsImpl@566a5c98
credentials: -> com.cloudbees.plugins.credentials.impl.UsernamePasswordCredentialsImpl@ce7e22e1
credentials: -> com.cloudbees.plugins.credentials.impl.UsernamePasswordCredentialsImpl@2536dbb1
credentials: -> SauceCredentials{apiKey={XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX, username='XXXXXXX', restEndpoint='null'}
credentials: -> com.cloudbees.jenkins.plugins.sshcredentials.impl.BasicSSHUserPrivateKey@d2164622
credentials: -> com.cloudbees.jenkins.plugins.awscredentials.AWSCredentialsImpl@30319aab
credentials: -> com.cloudbees.jenkins.plugins.awscredentials.AWSCredentialsImpl@51c1eca3
credentials: -> com.cloudbees.plugins.credentials.impl.UsernamePasswordCredentialsImpl@e849d24f
credentials: -> com.cloudbees.plugins.credentials.impl.UsernamePasswordCredentialsImpl@88ae1c0b
credentials: -> com.cloudbees.plugins.credentials.impl.UsernamePasswordCredentialsImpl@190595a8
credentials: -> org.jenkinsci.plugins.plaincredentials.impl.StringCredentialsImpl@c61542df
credentials: -> com.cloudbees.jenkins.plugins.sshcredentials.impl.BasicSSHUserPrivateKey@960e1225
credentials: -> com.cloudbees.jenkins.plugins.sshcredentials.impl.BasicSSHUserPrivateKey@c2ae43a
credentials: -> com.cloudbees.plugins.credentials.impl.UsernamePasswordCredentialsImpl@c231d8c5
credentials: -> com.cloudbees.plugins.credentials.impl.UsernamePasswordCredentialsImpl@64b98b2b
credentials: -> org.jenkinsci.plugins.plaincredentials.impl.StringCredentialsImpl@91f3761d
credentials: -> org.jenkinsci.plugins.plaincredentials.impl.StringCredentialsImpl@ca9d6fbe
credentials: -> com.cloudbees.plugins.credentials.impl.UsernamePasswordCredentialsImpl@ccf233cc
credentials: -> org.jenkinsci.plugins.plaincredentials.impl.StringCredentialsImpl@e762f20
credentials: -> com.cloudbees.plugins.credentials.impl.UsernamePasswordCredentialsImpl@302b8484
credentials: -> com.cloudbees.jenkins.plugins.awscredentials.AWSCredentialsImpl@27a34486
credentials: -> org.jenkinsci.plugins.plaincredentials.impl.StringCredentialsImpl@159f6d63
credentials: -> com.microsoft.jenkins.kubernetes.credentials.KubeconfigCredentials@94df54af
credentials: -> com.cloudbees.plugins.credentials.impl.CertificateCredentialsImpl@10e6b1da
credentials: -> com.microsoft.jenkins.kubernetes.credentials.KubeconfigCredentials@f72d9913
credentials: -> com.cloudbees.plugins.credentials.impl.UsernamePasswordCredentialsImpl@5b4765ac
credentials: -> com.cloudbees.plugins.credentials.impl.UsernamePasswordCredentialsImpl@fc8d023b
credentials: -> org.jenkinsci.plugins.plaincredentials.impl.FileCredentialsImpl@1065af2d
credentials: -> com.elasticbox.jenkins.k8s.plugin.auth.TokenCredentialsImpl@d6409031
credentials: -> org.jenkinsci.plugins.plaincredentials.impl.StringCredentialsImpl@cfdff5e4
credentials: -> com.cloudbees.plugins.credentials.impl.UsernamePasswordCredentialsImpl@2106b1b6
docker-custom-build-environment: 1.7.3
jquery-detached: 1.2.1
gradle: 1.32
build-pipeline-plugin: 1.5.8
multiple-scms: 0.6
authorize-project: 1.3.0
cloudbees-folder: 6.9
ws-cleanup: 0.37
durable-task: 1.29
plain-credentials: 1.5
pipeline-stage-view: 2.11
flexible-publish: 0.15.2
translation: 1.16
mask-passwords: 2.12.0
xvnc: 1.24
blueocean-commons: 1.17.0
async-http-client: 1.9.40.0
icon-shim: 2.0.3
kubernetes-pipeline-steps: 1.6
external-workspace-manager: 1.1.2
rebuild: 1.31
blueocean-pipeline-api-impl: 1.17.0
cloudbees-disk-usage-simple: 0.9
htmlpublisher: 1.18
jobConfigHistory: 2.22
handy-uri-templates-2-api: 2.1.7-1.0
github: 1.29.4
sonar: 2.9
blueocean-executor-info: 1.17.0
ant: 1.9
bouncycastle-api: 2.17
kubernetes-credentials: 0.4.0
nodejs: 1.3.1
maven-plugin: 3.2
blueocean-dashboard: 1.17.0
workflow-job: 2.32
kubernetes-credentials-provider: 0.12.1
config-file-provider: 3.6
blueocean-i18n: 1.17.0
kubernetes-pipeline-aggregator: 1.6
job-dsl: 1.74
splunk-devops: 1.7.3
pipeline-model-api: 1.3.9
workflow-step-api: 2.20
timestamper: 1.9
blueocean-bitbucket-pipeline: 1.17.0
publish-over-ssh: 1.20.1
dockerhub-notification: 2.4.0
build-blocker-plugin: 1.7.3
nested-view: 1.17
jquery-ui: 1.0.2
mapdb-api: 1.0.9.0
workflow-aggregator: 2.6
ldap: 1.20
blueocean-jira: 1.17.0
pipeline-model-declarative-agent: 1.1.1
kubernetes-ci: 1.3
docker-commons: 1.15
authentication-tokens: 1.3
blueocean-github-pipeline: 1.17.0
configuration-as-code: 1.20
pipeline-model-extensions: 1.3.9
maven-repo-cleaner: 1.2
blueocean-display-url: 2.3.0
pipeline-stage-tags-metadata: 1.3.9
job-restrictions: 0.8
blueocean-config: 1.17.0
configurationslicing: 1.47
workflow-multibranch: 2.21
jenkins-multijob-plugin: 1.32
throttle-concurrents: 2.0.1
cloudbees-bitbucket-branch-source: 2.4.4
aws-java-sdk: 1.11.562
blueocean-rest: 1.17.0
apache-httpcomponents-client-4-api: 4.5.5-3.0
copyartifact: 1.42.1
ssh-credentials: 1.17
matrix-project: 1.14
ssh-slaves: 1.30.0
docker-build-publish: 1.3.2
blueocean-web: 1.17.0
run-condition: 1.2
variant: 1.2
blueocean-pipeline-editor: 1.17.0
kubernetes-pipeline-devops-steps: 1.6
lockable-resources: 2.5
workflow-support: 3.3
branch-api: 2.5.2
built-on-column: 1.1
kubernetes-cli: 1.6.0
clone-workspace-scm: 0.6
display-url-api: 2.3.1
conditional-buildstep: 1.3.6
amazon-ecr: 1.6
envinject-api: 1.5
pam-auth: 1.5.1
momentjs: 1.1.1
bitbucket: 1.1.9
blueocean-personalization: 1.17.0
ace-editor: 1.1
saml: 1.1.2
jquery: 1.12.4-0
workflow-durable-task-step: 2.31
workflow-cps-global-lib: 2.13
m2release: 0.14.0
publish-over: 0.22
subversion: 2.12.1
pipeline-stage-step: 2.3
favorite: 2.3.2
token-macro: 2.8
docker-workflow: 1.18
blueocean-jwt: 1.17.0
external-monitor-job: 1.7
audit-trail: 2.5
git-client: 3.0.0-rc
blueocean-events: 1.17.0
azure-commons: 1.0.3
git-server: 1.7
bitbucket-build-status-notifier: 1.4.1
ivy: 2.1
blueocean-rest-impl: 1.17.0
jsch: 0.1.55
build-failure-analyzer: 1.22.0
blueocean-pipeline-scm-api: 1.17.0
javadoc: 1.5
kubernetes: 1.16.0
structs: 1.19
artifactory: 3.2.4
pipeline-rest-api: 2.11
blueocean-autofavorite: 1.2.4
git: 4.0.0-rc
matrix-auth: 2.4.2
docker-plugin: 1.1.6
node-iterator-api: 1.5
build-timeout: 1.19
mercurial: 2.6
configuration-as-code-secret-ssm: 1.0.0
handlebars: 1.1.1
antisamy-markup-formatter: 1.5
sauce-ondemand: 1.184
jdk-tool: 1.2
workflow-scm-step: 2.9
veracode-jenkins-plugin: 17.11.5.3
pipeline-milestone-step: 1.3.1
github-branch-source: 2.5.3
kubernetes-cd: 1.0.0
cvs: 2.14
pipeline-build-step: 2.9
pipeline-input-step: 2.10
trilead-api: 1.0.3
next-build-number: 1.5
role-strategy: 2.11
git-parameter: 0.9.10
workflow-api: 2.35
jackson2-api: 2.9.9
docker-traceability: 1.2
whitesource: 19.1.1
terraform: 1.0.9
build-name-setter: 2.0.1
blueocean-git-pipeline: 1.17.0
performance: 3.16
github-api: 1.95
ssh-agent: 1.17
promoted-builds: 3.2
sse-gateway: 1.17
ansicolor: 0.6.2
script-security: 1.60
jenkins-design-language: 1.17.0
mailer: 1.23
oic-auth: 1.6
ec2: 1.43
scm-api: 2.4.1
pipeline-model-definition: 1.3.9
junit: 1.28
analysis-core: 1.96
email-ext: 2.66
checkmarx: 8.90.1
packer: 1.5
monitoring: 1.77.0
xvfb: 1.1.3
aws-credentials: 1.27
jira: 3.0.7
pipeline-graph-analysis: 1.10
kubernetes-pipeline-arquillian-steps: 1.6
workflow-basic-steps: 2.18
groovy: 2.2
envinject: 2.1.6
windows-slaves: 1.4
pubsub-light: 1.12
credentials-binding: 1.19
resource-disposer: 0.12
docker-java-api: 3.0.14
blueocean: 1.17.0
command-launcher: 1.3
active-directory: 2.16
parameterized-trigger: 2.35.2
credentials: 2.2.0
amazon-ecs: 1.20
workflow-cps: 2.70
docker-build-step: 2.3
blueocean-core-js: 1.17.0
Result: [Plugin:docker-custom-build-environment, Plugin:jquery-detached, Plugin:gradle, Plugin:build-pipeline-plugin, Plugin:multiple-scms, Plugin:authorize-project, Plugin:cloudbees-folder, Plugin:ws-cleanup, Plugin:durable-task, Plugin:plain-credentials, Plugin:pipeline-stage-view, Plugin:flexible-publish, Plugin:translation, Plugin:mask-passwords, Plugin:xvnc, Plugin:blueocean-commons, Plugin:async-http-client, Plugin:icon-shim, Plugin:kubernetes-pipeline-steps, Plugin:external-workspace-manager, Plugin:rebuild, Plugin:blueocean-pipeline-api-impl, Plugin:cloudbees-disk-usage-simple, Plugin:htmlpublisher, Plugin:jobConfigHistory, Plugin:handy-uri-templates-2-api, Plugin:github, Plugin:sonar, Plugin:blueocean-executor-info, Plugin:ant, Plugin:bouncycastle-api, Plugin:kubernetes-credentials, Plugin:nodejs, Plugin:maven-plugin, Plugin:blueocean-dashboard, Plugin:workflow-job, Plugin:kubernetes-credentials-provider, Plugin:config-file-provider, Plugin:blueocean-i18n, Plugin:kubernetes-pipeline-aggregator, Plugin:job-dsl, Plugin:splunk-devops, Plugin:pipeline-model-api, Plugin:workflow-step-api, Plugin:timestamper, Plugin:blueocean-bitbucket-pipeline, Plugin:publish-over-ssh, Plugin:dockerhub-notification, Plugin:build-blocker-plugin, Plugin:nested-view, Plugin:jquery-ui, Plugin:mapdb-api, Plugin:workflow-aggregator, Plugin:ldap, Plugin:blueocean-jira, Plugin:pipeline-model-declarative-agent, Plugin:kubernetes-ci, Plugin:docker-commons, Plugin:authentication-tokens, Plugin:blueocean-github-pipeline, Plugin:configuration-as-code, Plugin:pipeline-model-extensions, Plugin:maven-repo-cleaner, Plugin:blueocean-display-url, Plugin:pipeline-stage-tags-metadata, Plugin:job-restrictions, Plugin:blueocean-config, Plugin:configurationslicing, Plugin:workflow-multibranch, Plugin:jenkins-multijob-plugin, Plugin:throttle-concurrents, Plugin:cloudbees-bitbucket-branch-source, Plugin:aws-java-sdk, Plugin:blueocean-rest, Plugin:apache-httpcomponents-client-4-api, Plugin:copyartifact, Plugin:ssh-credentials, Plugin:matrix-project, Plugin:ssh-slaves, Plugin:docker-build-publish, Plugin:blueocean-web, Plugin:run-condition, Plugin:variant, Plugin:blueocean-pipeline-editor, Plugin:kubernetes-pipeline-devops-steps, Plugin:lockable-resources, Plugin:workflow-support, Plugin:branch-api, Plugin:built-on-column, Plugin:kubernetes-cli, Plugin:clone-workspace-scm, Plugin:display-url-api, Plugin:conditional-buildstep, Plugin:amazon-ecr, Plugin:envinject-api, Plugin:pam-auth, Plugin:momentjs, Plugin:bitbucket, Plugin:blueocean-personalization, Plugin:ace-editor, Plugin:saml, Plugin:jquery, Plugin:workflow-durable-task-step, Plugin:workflow-cps-global-lib, Plugin:m2release, Plugin:publish-over, Plugin:subversion, Plugin:pipeline-stage-step, Plugin:favorite, Plugin:token-macro, Plugin:docker-workflow, Plugin:blueocean-jwt, Plugin:external-monitor-job, Plugin:audit-trail, Plugin:git-client, Plugin:blueocean-events, Plugin:azure-commons, Plugin:git-server, Plugin:bitbucket-build-status-notifier, Plugin:ivy, Plugin:blueocean-rest-impl, Plugin:jsch, Plugin:build-failure-analyzer, Plugin:blueocean-pipeline-scm-api, Plugin:javadoc, Plugin:kubernetes, Plugin:structs, Plugin:artifactory, Plugin:pipeline-rest-api, Plugin:blueocean-autofavorite, Plugin:git, Plugin:matrix-auth, Plugin:docker-plugin, Plugin:node-iterator-api, Plugin:build-timeout, Plugin:mercurial, Plugin:configuration-as-code-secret-ssm, Plugin:handlebars, Plugin:antisamy-markup-formatter, Plugin:sauce-ondemand, Plugin:jdk-tool, Plugin:workflow-scm-step, Plugin:veracode-jenkins-plugin, Plugin:pipeline-milestone-step, Plugin:github-branch-source, Plugin:kubernetes-cd, Plugin:cvs, Plugin:pipeline-build-step, Plugin:pipeline-input-step, Plugin:trilead-api, Plugin:next-build-number, Plugin:role-strategy, Plugin:git-parameter, Plugin:workflow-api, Plugin:jackson2-api, Plugin:docker-traceability, Plugin:whitesource, Plugin:terraform, Plugin:build-name-setter, Plugin:blueocean-git-pipeline, Plugin:performance, Plugin:github-api, Plugin:ssh-agent, Plugin:promoted-builds, Plugin:sse-gateway, Plugin:ansicolor, Plugin:script-security, Plugin:jenkins-design-language, Plugin:mailer, Plugin:oic-auth, Plugin:ec2, Plugin:scm-api, Plugin:pipeline-model-definition, Plugin:junit, Plugin:analysis-core, Plugin:email-ext, Plugin:checkmarx, Plugin:packer, Plugin:monitoring, Plugin:xvfb, Plugin:aws-credentials, Plugin:jira, Plugin:pipeline-graph-analysis, Plugin:kubernetes-pipeline-arquillian-steps, Plugin:workflow-basic-steps, Plugin:groovy, Plugin:envinject, Plugin:windows-slaves, Plugin:pubsub-light, Plugin:credentials-binding, Plugin:resource-disposer, Plugin:docker-java-api, Plugin:blueocean, Plugin:command-launcher, Plugin:active-directory, Plugin:parameterized-trigger, Plugin:credentials, Plugin:amazon-ecs, Plugin:workflow-cps, Plugin:docker-build-step, Plugin:blueocean-core-js]

**Comment by casz** [comment]
I am going take stab at guessing `SauceCredentials` is the one not compatible since that the only one I am unsure whether it supports JCasC.
Rest of the credential classes I know :sweat_smile: 

Also seems like SauceCredentials doesn't care about using a secret even though it is a credential type.
This [String](https://github.com/jenkinsci/sauce-ondemand-plugin/blob/master/src/main/java/hudson/plugins/sauce_ondemand/credentials/SauceCredentials.java#L59) should have been a secret :cry: 

we would need to add more credential integrations tests to find the exact sinner.

**Comment by yrsurya** [comment]
I can provide if any more details needed or do you want me to open a ticket for saucelabs Jenkins plugin?

**Comment by casz** [comment]
I'd need to verify

**Comment by yrsurya** [comment]
okay thanks for checking....

**Comment by timja** [comment]
Sauce is compatible
https://github.com/hmcts/cnp-jenkins-config/blob/master/cac-test-local.yml#L364

Where's it not a string? I fixed one issue in the sauce plugin where it was using a string instead of a secret in the jelly

**Comment by casz** [comment]
Perhaps the new Certificate Credential security fix is at fault.
https://jenkins.io/security/advisory/2019-05-21/#SECURITY-1322 added in credential 2.1.19

**Comment by yrsurya** [comment]
Please let me know if you want me to create a new ticket to track saucelabs issue ? @casz

**Comment by casz** [comment]
@yrsurya as @timja said sauce plugin works 😓

**Comment by yrsurya** [comment]
I removed the sauce credentials along with sauce plugin form Jenkins and restarted still seeing same issue while exporting 
Result
credentials:
com.cloudbees.plugins.credentials.impl.UsernamePasswordCredentialsImpl@8418f71a
com.cloudbees.plugins.credentials.impl.UsernamePasswordCredentialsImpl@5de67046
com.cloudbees.plugins.credentials.impl.UsernamePasswordCredentialsImpl@3ed176d3
com.cloudbees.jenkins.plugins.sshcredentials.impl.BasicSSHUserPrivateKey@be348040
com.cloudbees.jenkins.plugins.sshcredentials.impl.BasicSSHUserPrivateKey@aa03297a
com.cloudbees.plugins.credentials.impl.UsernamePasswordCredentialsImpl@78477e42
com.cloudbees.jenkins.plugins.sshcredentials.impl.BasicSSHUserPrivateKey@9bf4a920
com.cloudbees.jenkins.plugins.awscredentials.AWSCredentialsImpl@b3b76433
com.cloudbees.plugins.credentials.impl.UsernamePasswordCredentialsImpl@566a5c98
com.cloudbees.plugins.credentials.impl.UsernamePasswordCredentialsImpl@ce7e22e1
com.cloudbees.plugins.credentials.impl.UsernamePasswordCredentialsImpl@2536dbb1
com.cloudbees.jenkins.plugins.sshcredentials.impl.BasicSSHUserPrivateKey@d2164622
com.cloudbees.jenkins.plugins.awscredentials.AWSCredentialsImpl@30319aab
com.cloudbees.jenkins.plugins.awscredentials.AWSCredentialsImpl@51c1eca3
com.cloudbees.plugins.credentials.impl.UsernamePasswordCredentialsImpl@e849d24f
com.cloudbees.plugins.credentials.impl.UsernamePasswordCredentialsImpl@88ae1c0b
com.cloudbees.plugins.credentials.impl.UsernamePasswordCredentialsImpl@190595a8
org.jenkinsci.plugins.plaincredentials.impl.StringCredentialsImpl@c61542df
com.cloudbees.jenkins.plugins.sshcredentials.impl.BasicSSHUserPrivateKey@960e1225
com.cloudbees.jenkins.plugins.sshcredentials.impl.BasicSSHUserPrivateKey@c2ae43a
com.cloudbees.plugins.credentials.impl.UsernamePasswordCredentialsImpl@c231d8c5
com.cloudbees.plugins.credentials.impl.UsernamePasswordCredentialsImpl@64b98b2b
org.jenkinsci.plugins.plaincredentials.impl.StringCredentialsImpl@91f3761d
org.jenkinsci.plugins.plaincredentials.impl.StringCredentialsImpl@ca9d6fbe
com.cloudbees.plugins.credentials.impl.UsernamePasswordCredentialsImpl@ccf233cc
org.jenkinsci.plugins.plaincredentials.impl.StringCredentialsImpl@e762f20
com.cloudbees.plugins.credentials.impl.UsernamePasswordCredentialsImpl@302b8484
com.cloudbees.jenkins.plugins.awscredentials.AWSCredentialsImpl@27a34486
org.jenkinsci.plugins.plaincredentials.impl.StringCredentialsImpl@159f6d63
com.microsoft.jenkins.kubernetes.credentials.KubeconfigCredentials@94df54af
com.cloudbees.plugins.credentials.impl.CertificateCredentialsImpl@10e6b1da
com.microsoft.jenkins.kubernetes.credentials.KubeconfigCredentials@f72d9913
com.cloudbees.plugins.credentials.impl.UsernamePasswordCredentialsImpl@5b4765ac
com.cloudbees.plugins.credentials.impl.UsernamePasswordCredentialsImpl@fc8d023b
org.jenkinsci.plugins.plaincredentials.impl.FileCredentialsImpl@1065af2d
com.elasticbox.jenkins.k8s.plugin.auth.TokenCredentialsImpl@d6409031
org.jenkinsci.plugins.plaincredentials.impl.StringCredentialsImpl@cfdff5e4
com.cloudbees.plugins.credentials.impl.UsernamePasswordCredentialsImpl@2106b1b6

plugins:
ace-editor: 1.1
active-directory: 2.16
amazon-ecr: 1.6
amazon-ecs: 1.20
analysis-core: 1.96
ansicolor: 0.6.2
ant: 1.9
antisamy-markup-formatter: 1.5
apache-httpcomponents-client-4-api: 4.5.5-3.0
artifactory: 3.3.0
async-http-client: 1.9.40.0
audit-trail: 2.5
authentication-tokens: 1.3
authorize-project: 1.3.0
aws-credentials: 1.27
aws-java-sdk: 1.11.562
azure-commons: 1.0.3
bitbucket: 1.1.9
bitbucket-build-status-notifier: 1.4.1
blueocean: 1.17.0
blueocean-autofavorite: 1.2.4
blueocean-bitbucket-pipeline: 1.17.0
blueocean-commons: 1.17.0
blueocean-config: 1.17.0
blueocean-core-js: 1.17.0
blueocean-dashboard: 1.17.0
blueocean-display-url: 2.3.0
blueocean-events: 1.17.0
blueocean-executor-info: 1.17.0
blueocean-git-pipeline: 1.17.0
blueocean-github-pipeline: 1.17.0
blueocean-i18n: 1.17.0
blueocean-jira: 1.17.0
blueocean-jwt: 1.17.0
blueocean-personalization: 1.17.0
blueocean-pipeline-api-impl: 1.17.0
blueocean-pipeline-editor: 1.17.0
blueocean-pipeline-scm-api: 1.17.0
blueocean-rest: 1.17.0
blueocean-rest-impl: 1.17.0
blueocean-web: 1.17.0
bouncycastle-api: 2.17
branch-api: 2.5.2
build-blocker-plugin: 1.7.3
build-failure-analyzer: 1.22.0
build-name-setter: 2.0.1
build-pipeline-plugin: 1.5.8
build-timeout: 1.19
built-on-column: 1.1
checkmarx: 8.80.3
clone-workspace-scm: 0.6
cloudbees-bitbucket-branch-source: 2.4.4
cloudbees-disk-usage-simple: 0.9
cloudbees-folder: 6.9
command-launcher: 1.3
conditional-buildstep: 1.3.6
config-file-provider: 3.6
configuration-as-code: 1.20
configuration-as-code-secret-ssm: 1.0.0
configurationslicing: 1.47
copyartifact: 1.42.1
credentials: 2.2.0
credentials-binding: 1.19
cvs: 2.14
display-url-api: 2.3.1
docker-build-publish: 1.3.2
docker-build-step: 2.3
docker-commons: 1.15
docker-custom-build-environment: 1.7.3
docker-java-api: 3.0.14
docker-plugin: 1.1.6
docker-traceability: 1.2
docker-workflow: 1.18
dockerhub-notification: 2.4.0
durable-task: 1.29
ec2: 1.43
email-ext: 2.66
envinject: 2.1.6
envinject-api: 1.5
external-monitor-job: 1.7
external-workspace-manager: 1.1.2
favorite: 2.3.2
flexible-publish: 0.15.2
git: 4.0.0-rc
git-client: 3.0.0-rc
git-parameter: 0.9.10
git-server: 1.7
github: 1.29.4
github-api: 1.95
github-branch-source: 2.5.3
gradle: 1.32
groovy: 2.2
handlebars: 1.1.1
handy-uri-templates-2-api: 2.1.7-1.0
htmlpublisher: 1.18
icon-shim: 2.0.3
ivy: 2.1
jackson2-api: 2.9.9
javadoc: 1.5
jdk-tool: 1.2
jenkins-design-language: 1.17.0
jenkins-multijob-plugin: 1.32
jira: 3.0.7
job-dsl: 1.74
job-restrictions: 0.8
jobConfigHistory: 2.22
jquery: 1.12.4-0
jquery-detached: 1.2.1
jquery-ui: 1.0.2
jsch: 0.1.55
junit: 1.28
kubernetes: 1.16.0
kubernetes-cd: 1.0.0
kubernetes-ci: 1.3
kubernetes-cli: 1.6.0
kubernetes-credentials: 0.4.0
kubernetes-credentials-provider: 0.12.1
kubernetes-pipeline-aggregator: 1.6
kubernetes-pipeline-arquillian-steps: 1.6
kubernetes-pipeline-devops-steps: 1.6
kubernetes-pipeline-steps: 1.6
ldap: 1.20
lockable-resources: 2.5
m2release: 0.14.0
mailer: 1.23
mapdb-api: 1.0.9.0
mask-passwords: 2.12.0
matrix-auth: 2.4.2
matrix-project: 1.14
maven-plugin: 3.3
maven-repo-cleaner: 1.2
mercurial: 2.6
momentjs: 1.1.1
monitoring: 1.77.0
multiple-scms: 0.6
nested-view: 1.17
next-build-number: 1.5
node-iterator-api: 1.5
nodejs: 1.3.2
oic-auth: 1.6
packer: 1.5
pam-auth: 1.5.1
parameterized-trigger: 2.35.2
performance: 3.17
pipeline-build-step: 2.9
pipeline-graph-analysis: 1.10
pipeline-input-step: 2.10
pipeline-milestone-step: 1.3.1
pipeline-model-api: 1.3.9
pipeline-model-declarative-agent: 1.1.1
pipeline-model-definition: 1.3.9
pipeline-model-extensions: 1.3.9
pipeline-rest-api: 2.11
pipeline-stage-step: 2.3
pipeline-stage-tags-metadata: 1.3.9
pipeline-stage-view: 2.11
plain-credentials: 1.5
promoted-builds: 3.2
publish-over: 0.22
publish-over-ssh: 1.20.1
pubsub-light: 1.12
rebuild: 1.31
resource-disposer: 0.12
role-strategy: 2.11
run-condition: 1.2
saml: 1.1.2
scm-api: 2.5.0
script-security: 1.60
sonar: 2.9
splunk-devops: 1.7.4
sse-gateway: 1.17
ssh-agent: 1.17
ssh-credentials: 1.17
ssh-slaves: 1.30.0
structs: 1.19
subversion: 2.12.1
terraform: 1.0.9
throttle-concurrents: 2.0.1
timestamper: 1.9
token-macro: 2.8
translation: 1.16
trilead-api: 1.0.3
variant: 1.2
veracode-jenkins-plugin: 17.11.5.3
whitesource: 19.1.1
windows-slaves: 1.4
workflow-aggregator: 2.6
workflow-api: 2.35
workflow-basic-steps: 2.18
workflow-cps: 2.70
workflow-cps-global-lib: 2.13
workflow-durable-task-step: 2.31
workflow-job: 2.32
workflow-multibranch: 2.21
workflow-scm-step: 2.9
workflow-step-api: 2.20
workflow-support: 3.3
ws-cleanup: 0.37
xvfb: 1.1.3
xvnc: 1.24

credentials:
  system:
    domainCredentials:
    - credentials: "FAILED TO EXPORT com.cloudbees.plugins.credentials.domains.DomainCredentials#credentials:\
        \ java.lang.NullPointerException  at io.jenkins.plugins.casc.impl.configurators.DataBoundConfigurator.describe(DataBoundConfigurator.java:240)\
        \  at io.jenkins.plugins.casc.impl.configurators.HeteroDescribableConfigurator.lambda$convertToNode$de0cd4f8$1(HeteroDescribableConfigurator.java:224)\
        \  at io.vavr.CheckedFunction0.lambda$unchecked$52349c75$1(CheckedFunction0.java:201)\
        \  at io.jenkins.plugins.casc.impl.configurators.HeteroDescribableConfigurator.convertToNode(HeteroDescribableConfigurator.java:224)\
        \  at io.jenkins.plugins.casc.impl.configurators.HeteroDescribableConfigurator.lambda$describe$5(HeteroDescribableConfigurator.java:103)\
        \  at io.vavr.control.Option.map(Option.java:373)  at io.jenkins.plugins.casc.impl.configurators.HeteroDescribableConfigurator.describe(HeteroDescribableConfigurator.java:103)\
        \  at io.jenkins.plugins.casc.impl.configurators.HeteroDescribableConfigurator.describe(HeteroDescribableConfigurator.java:51)\
        \  at io.jenkins.plugins.casc.Attribute.describe(Attribute.java:194)  at io.jenkins.plugins.casc.impl.configurators.DataBoundConfigurator.describe(DataBoundConfigurator.java:264)\
        \  at io.jenkins.plugins.casc.Attribute.describe(Attribute.java:194)  at com.cloudbees.plugins.credentials.casc.SystemCredentialsProviderConfigurator.describe(SystemCredentialsProviderConfigurator.java:76)\
        \  at com.cloudbees.plugins.credentials.casc.SystemCredentialsProviderConfigurator.describe(SystemCredentialsProviderConfigurator.java:48)\
        \  at io.jenkins.plugins.casc.Attribute.describe(Attribute.java:198)  at com.cloudbees.plugins.credentials.casc.CredentialsRootConfigurator.describe(CredentialsRootConfigurator.java:90)\
        \  at com.cloudbees.plugins.credentials.casc.CredentialsRootConfigurator.describe(CredentialsRootConfigurator.java:52)"
jenkins:

**Comment by courteouselk** [comment]
There is a similar issue with "Perforce password credential".  If I configure one on my system (jenkins v2.176.1, p4 plugin v1.10.0, class org.jenkinsci.plugins.p4.credentials.P4PasswordImpl) then I get the following error:

```
credentials:
  system:
    domainCredentials:
    - credentials: "FAILED TO EXPORT com.cloudbees.plugins.credentials.domains.DomainCredentials#credentials:\
        \ java.lang.IllegalArgumentException: argument type mismatch  at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native\
        \ Method)  at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)\
        \  at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)\
        \  at java.lang.reflect.Constructor.newInstance(Constructor.java:423)  at\
        \ io.jenkins.plugins.casc.impl.configurators.DataBoundConfigurator.describe(DataBoundConfigurator.java:255)\
        \  at io.jenkins.plugins.casc.impl.configurators.HeteroDescribableConfigurator.lambda$convertToNode$de0cd4f8$1(HeteroDescribableConfigurator.java:224)\
        \  at io.vavr.CheckedFunction0.lambda$unchecked$52349c75$1(CheckedFunction0.java:201)\
        \  at io.jenkins.plugins.casc.impl.configurators.HeteroDescribableConfigurator.convertToNode(HeteroDescribableConfigurator.java:224)\
        \  at io.jenkins.plugins.casc.impl.configurators.HeteroDescribableConfigurator.lambda$describe$5(HeteroDescribableConfigurator.java:103)\
        \  at io.vavr.control.Option.map(Option.java:373)  at io.jenkins.plugins.casc.impl.configurators.HeteroDescribableConfigurator.describe(HeteroDescribableConfigurator.java:103)\
        \  at io.jenkins.plugins.casc.impl.configurators.HeteroDescribableConfigurator.describe(HeteroDescribableConfigurator.java:51)\
        \  at io.jenkins.plugins.casc.Attribute.describe(Attribute.java:194)  at io.jenkins.plugins.casc.impl.configurators.DataBoundConfigurator.describe(DataBoundConfigurator.java:264)\
        \  at io.jenkins.plugins.casc.Attribute.describe(Attribute.java:194)  at com.cloudbees.plugins.credentials.casc.SystemCredentialsProviderConfigurator.describe(SystemCredentialsProviderConfigurator.java:76)\
        \  at com.cloudbees.plugins.credentials.casc.SystemCredentialsProviderConfigurator.describe(SystemCredentialsProviderConfigurator.java:48)\
        \  at io.jenkins.plugins.casc.Attribute.describe(Attribute.java:198)  at com.cloudbees.plugins.credentials.casc.CredentialsRootConfigurator.describe(CredentialsRootConfigurator.java:90)\
        \  at com.cloudbees.plugins.credentials.casc.CredentialsRootConfigurator.describe(CredentialsRootConfigurator.java:52)"
```

**Comment by yrsurya** [comment]
I am able to get rid of this error after removing a secret file credential which is using plain credentials plugin

**Comment by casz** [comment]
@courteouselk that would be a plugin compatibility issue with P4 credentials

**Comment by courteouselk** [comment]
Thanks @casz. I created a new issue then: https://github.com/jenkinsci/configuration-as-code-plugin/issues/934
